In [2]:
#100 big12 conference games, choosing 35, less downloading
import numpy as np

sample = np.random.choice(range(1, 96), 35, replace=False)
print(sample)

[49 21 61 88 60  4 42 92 84 90 30 47 85 76 14 38 55 35 53 94 37 15 75 62
 65 50 77 18 68 20 87 26 36  3 54]

In [52]:
import pandas as pd
pd.set_option('display.max_columns', None)

from functions import (
    compute_shot_chain_scores,
    parse_player_data_xml,
    add_team_name,
    plot_keeper_dist,
    parse_team_data_xml,
)

#Set WD - important
from pathlib import Path

PROJECT_ROOT = Path.cwd()
DATA_FOLDER = PROJECT_ROOT / "2025_data" / "big12_random_35_games"

In [53]:
team_data = parse_team_data_xml(
    folder=DATA_FOLDER,
    files="ASU Sun Devils - TCU Frogs 1-2 (Team-based).xml"
)

print("Rows, Columns:", team_data.shape)
display(team_data.head())

Rows, Columns: (1031, 21)

,match_name,ID,code,start,end,01 - Location third,02 - Location flank,03 - End location third,04 - End location flank,05 - Length,06 - Number of team events,10 - Players,11 - Start location X,12 - Start location Y,13 - Duration,14 - Formation,15 - End location X,16 - End location Y,08 - Transition,07 - Outcome,09 - xG
0,ASU Sun Devils - TCU Frogs 1-2 (Team-based),1,Ball in play,30.281318,35.124629,Middle third,Center,Final third,Left flank,Short,4 or less,4. Gillard,53.0,35.0,2.0,4-2-3-1,12.0,68.0,NaN,NaN,NaN
1,ASU Sun Devils - TCU Frogs 1-2 (Team-based),2,ASU Sun Devils - Possessions,30.281318,35.124629,Middle third,Center,Final third,Left flank,Short,4 or less,4. Gillard,53.0,35.0,2.0,4-2-3-1,12.0,68.0,NaN,NaN,NaN
2,ASU Sun Devils - TCU Frogs 1-2 (Team-based),3,Ball in play,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN
3,ASU Sun Devils - TCU Frogs 1-2 (Team-based),4,TCU Frogs - Possessions,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN
4,ASU Sun Devils - TCU Frogs 1-2 (Team-based),5,TCU Frogs - Set Pieces,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN

In [48]:
print(team_data['code'].unique())

<StringArray>
[                             'Ball in play',
              'ASU Sun Devils - Possessions',
                   'TCU Frogs - Possessions',
                    'TCU Frogs - Set Pieces',
                     'TCU Frogs - Throw ins',
      'TCU Frogs - Goalkeeper distributions',
             'TCU Frogs - Open play attacks',
                    'TCU Frogs - Highlights',
                         'TCU Frogs - Shots',
 'ASU Sun Devils - Goalkeeper distributions',
               'ASU Sun Devils - Set Pieces',
                'ASU Sun Devils - Throw ins',
               'ASU Sun Devils - Highlights',
                  'ASU Sun Devils - Corners',
        'ASU Sun Devils - Open play attacks',
                  'ASU Sun Devils - Crosses',
                    'ASU Sun Devils - Shots',
                       'TCU Frogs - Corners',
               'ASU Sun Devils - Free kicks',
                    'TCU Frogs - Free kicks',
                       'TCU Frogs - Crosses',
                         'TCU Frogs - Goals',
                    'ASU Sun Devils - Goals',
                                   'Periods']
Length: 24, dtype: str

In [ ]:
team_data.iloc[90:500][['code', '11 - Start location X', '12 - Start location Y', '15 - End location X', '16 - End location Y']]

In [56]:
player_data = parse_player_data_xml(
    folder=DATA_FOLDER,
    files="ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml",
    numeric_cols=["ID", "Start Time", "End Time"]
)

print("Rows, Columns:", player_data.shape)
display(player_data.head())

Rows, Columns: (1504, 7)

,Source File,ID,Player Code,Start Time,End Time,Action Type,Additional Labels
0,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,1,4. Gillard,27.281318,35.114629,Pass,"Forward pass, Long pass, Pass to final third"
1,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,2,17. Patton,41.008637,45.008637,Throw in,
2,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,3,2. S.Becerra,42.139294,47.873396,Pass,"Back pass, Short or medium pass"
3,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,4,23. Coppinger,44.873396,49.873396,Pass,"Forward pass, Loss, Progressive pass, Short or..."
4,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,5,11. Baltodano,46.655943,50.655943,Interception,Loss

In [57]:
display(player_data.head(50))

,Source File,ID,Player Code,Start Time,End Time,Action Type,Additional Labels
0,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,1,4. Gillard,27.281318,35.114629,Pass,"Forward pass, Long pass, Pass to final third"
1,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,2,17. Patton,41.008637,45.008637,Throw in,
2,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,3,2. S.Becerra,42.139294,47.873396,Pass,"Back pass, Short or medium pass"
3,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,4,23. Coppinger,44.873396,49.873396,Pass,"Forward pass, Loss, Progressive pass, Short or..."
4,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,5,11. Baltodano,46.655943,50.655943,Interception,Loss
5,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,6,1. Geller,56.636425,60.636425,Goal kick,Goalkeeper action
6,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,7,19. Brown,57.874294,61.874294,Touch,Carry
7,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,8,19. Brown,59.973350,66.898939,Pass,"Lateral pass, Short or medium pass"
8,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,9,23. Coppinger,63.898939,70.878258,Pass,"Lateral pass, Short or medium pass"
9,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,10,19. Brown,67.878258,73.860254,Pass,"Lateral pass, Short or medium pass"
10,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,11,23. Coppinger,70.860254,76.126548,Pass,"Lateral pass, Short or medium pass"
11,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,12,16. Sarinopoulos,74.126548,78.126548,Duel,"Foul suffered, Ground duel, Offensive duel"
12,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,13,11. Baltodano,74.126548,78.126548,Duel,"Defensive duel, Ground duel"
13,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,14,11. Baltodano,72.075756,79.075756,Infraction,Foul
14,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,15,23. Coppinger,91.495669,95.495669,Free kick,
15,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,16,19. Brown,93.282183,98.650610,Pass,"Lateral pass, Short or medium pass"
16,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,17,18. Yolinsky,95.650610,100.650610,Pass,"Forward pass, Short or medium pass"
17,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,18,9. Norman,98.439989,102.439989,Touch,Carry
18,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,19,9. Norman,98.408438,103.408438,Pass,"Forward pass, Short or medium pass"
19,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,20,10. Fuller,99.802489,104.802489,Pass,"Loss, Short or medium pass"
20,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,21,20. Valladares,101.506525,105.506525,Interception,
21,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,22,9. Norman,105.397360,109.397360,Throw in,
22,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,23,10. Fuller,107.183646,112.183646,Pass,"Back pass, Loss, Short or medium pass"
23,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,24,10. Mibe,108.836852,112.836852,Interception,"Loss, Recovery, Counterpressing recovery"
24,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,25,2. S.Becerra,111.021024,117.059975,Pass,"Lateral pass, Recovery, Counterpressing recove..."
25,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,26,23. Coppinger,114.059975,119.957367,Pass,"Lateral pass, Short or medium pass"
26,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,27,17. Patton,116.957367,121.957367,Pass,"Forward pass, Pass to final third, Progressive..."
27,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,28,15. Nunley,119.574812,123.574812,Duel,"Defensive duel, Ground duel, Recovery"
28,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,29,15. Nunley,121.295870,125.295870,Touch,
29,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,30,3. Hennessey,123.674119,127.674119,Duel,"Defensive duel, Ground duel, Recovery, Counter..."
30,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,31,15. Nunley,123.674119,127.674119,Duel,"Ground duel, Loss, Offensive duel"
31,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,32,3. Hennessey,127.562850,133.865321,Pass,"Lateral pass, Short or medium pass"
32,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,33,16. Sarinopoulos,130.865321,138.145922,Pass,"Back pass, Short or medium pass"
33,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,34,19. Brown,135.145922,140.582951,Pass,"Lateral pass, Short or medium pass"
34,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,35,23. Coppinger,137.582951,144.147343,Pass,"Forward pass, Pass to final third, Short or me..."
35,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,36,17. Patton,141.147343,146.685225,Pass,"Back pass, Short or medium pass"
36,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,37,23. Coppinger,143.685225,152.480904,Pass,"Lateral pass, Short or medium pass"
37,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,38,19. Brown,149.480904,155.753954,Pass,"Lateral pass, Short or medium pass"
38,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,39,9. Norman,152.753954,157.753954,Pass,"Forward pass, Loss, Short or medium pass"
39,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,40,18. Monck,153.975876,158.975876,Interception,"Forward pass, Pass, Short or medium pass"
40,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,41,10. Fuller,155.589577,159.589577,Touch,
41,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,42,11. Baltodano,158.498263,162.498263,Interception,Loss
42,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,43,16. Sarinopoulos,158.540934,164.498406,Pass,"Back pass, Recovery, Counterpressing recovery,..."
43,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,44,1. Geller,161.498406,168.426428,Pass,"Forward pass, Goalkeeper action, Short or medi..."
44,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,45,23. Coppinger,165.426428,174.745809,Pass,"Forward pass, Long pass, Pass to final third, ..."
45,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,46,7. Castain,171.745809,176.745809,Pass,"Back pass, Short or medium pass"
46,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,47,3. Hennessey,173.299024,178.704493,Pass,Short or medium pass
47,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,48,17. Patton,175.704493,181.042104,Pass,"Key pass, Lateral pass, Short or medium pass, ..."
48,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,49,6. Marcisz,178.791606,182.791606,Duel,"Defensive duel, Ground duel"
49,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,50,10. Fuller,179.042104,183.042104,Duel,"Dribble, Ground duel, Offensive duel"

In [58]:
display(team_data.head(50))

,match_name,ID,code,start,end,01 - Location third,02 - Location flank,03 - End location third,04 - End location flank,05 - Length,06 - Number of team events,10 - Players,11 - Start location X,12 - Start location Y,13 - Duration,14 - Formation,15 - End location X,16 - End location Y,08 - Transition,07 - Outcome,09 - xG
0,ASU Sun Devils - TCU Frogs 1-2 (Team-based),1,Ball in play,30.281318,35.124629,Middle third,Center,Final third,Left flank,Short,4 or less,4. Gillard,53.0,35.0,2.0,4-2-3-1,12.0,68.0,NaN,NaN,NaN
1,ASU Sun Devils - TCU Frogs 1-2 (Team-based),2,ASU Sun Devils - Possessions,30.281318,35.124629,Middle third,Center,Final third,Left flank,Short,4 or less,4. Gillard,53.0,35.0,2.0,4-2-3-1,12.0,68.0,NaN,NaN,NaN
2,ASU Sun Devils - TCU Frogs 1-2 (Team-based),3,Ball in play,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN
3,ASU Sun Devils - TCU Frogs 1-2 (Team-based),4,TCU Frogs - Possessions,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN
4,ASU Sun Devils - TCU Frogs 1-2 (Team-based),5,TCU Frogs - Set Pieces,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN
5,ASU Sun Devils - TCU Frogs 1-2 (Team-based),6,TCU Frogs - Throw ins,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN
6,ASU Sun Devils - TCU Frogs 1-2 (Team-based),7,Ball in play,48.655943,50.247034,Final third,Left flank,Final third,Left flank,Short,4 or less,11. Baltodano,97.0,8.0,1.0,4-2-3-1,0.0,61.0,NaN,NaN,NaN
7,ASU Sun Devils - TCU Frogs 1-2 (Team-based),8,ASU Sun Devils - Possessions,48.655943,50.247034,Final third,Left flank,Final third,Left flank,Short,4 or less,11. Baltodano,97.0,8.0,1.0,4-2-3-1,0.0,61.0,NaN,NaN,NaN
8,ASU Sun Devils - TCU Frogs 1-2 (Team-based),9,Ball in play,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
9,ASU Sun Devils - TCU Frogs 1-2 (Team-based),10,TCU Frogs - Possessions,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
10,ASU Sun Devils - TCU Frogs 1-2 (Team-based),11,TCU Frogs - Goalkeeper distributions,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
11,ASU Sun Devils - TCU Frogs 1-2 (Team-based),12,Ball in play,93.495669,103.516525,Own third,Center,Middle third,Left flank,Short,5-9,"23. Coppinger, 19. Brown, 18. Yolinsky, 9. Nor...",25.0,44.0,10.0,4-3-3,41.0,61.0,NaN,NaN,NaN
12,ASU Sun Devils - TCU Frogs 1-2 (Team-based),13,TCU Frogs - Possessions,93.495669,103.516525,Own third,Center,Middle third,Left flank,Short,5-9,"23. Coppinger, 19. Brown, 18. Yolinsky, 9. Nor...",25.0,44.0,10.0,4-3-3,41.0,61.0,NaN,NaN,NaN
13,ASU Sun Devils - TCU Frogs 1-2 (Team-based),14,Ball in play,103.506525,105.027079,Middle third,Right flank,Middle third,Right flank,Short,4 or less,20. Valladares,41.0,61.0,1.0,4-2-3-1,66.0,0.0,NaN,NaN,NaN
14,ASU Sun Devils - TCU Frogs 1-2 (Team-based),15,ASU Sun Devils - Possessions,103.506525,105.027079,Middle third,Right flank,Middle third,Right flank,Short,4 or less,20. Valladares,41.0,61.0,1.0,4-2-3-1,66.0,0.0,NaN,NaN,NaN
15,ASU Sun Devils - TCU Frogs 1-2 (Team-based),16,Ball in play,106.397360,110.846852,Middle third,Left flank,Middle third,Left flank,Short,4 or less,"9. Norman, 10. Fuller",64.0,0.0,3.0,4-3-3,40.0,62.0,NaN,NaN,NaN
16,ASU Sun Devils - TCU Frogs 1-2 (Team-based),17,TCU Frogs - Possessions,106.397360,110.846852,Middle third,Left flank,Middle third,Left flank,Short,4 or less,"9. Norman, 10. Fuller",64.0,0.0,3.0,4-3-3,40.0,62.0,NaN,NaN,NaN
17,ASU Sun Devils - TCU Frogs 1-2 (Team-based),18,TCU Frogs - Set Pieces,106.397360,110.846852,Middle third,Left flank,Middle third,Left flank,Short,4 or less,"9. Norman, 10. Fuller",64.0,0.0,3.0,4-3-3,40.0,62.0,NaN,NaN,NaN
18,ASU Sun Devils - TCU Frogs 1-2 (Team-based),19,TCU Frogs - Throw ins,106.397360,110.846852,Middle third,Left flank,Middle third,Left flank,Short,4 or less,"9. Norman, 10. Fuller",64.0,0.0,3.0,4-3-3,40.0,62.0,NaN,NaN,NaN
19,ASU Sun Devils - TCU Frogs 1-2 (Team-based),20,Ball in play,110.836852,114.031024,Middle third,Right flank,Middle third,Right flank,Short,4 or less,10. Mibe,40.0,62.0,2.0,4-2-3-1,65.0,13.0,NaN,NaN,NaN
20,ASU Sun Devils - TCU Frogs 1-2 (Team-based),21,ASU Sun Devils - Possessions,110.836852,114.031024,Middle third,Right flank,Middle third,Right flank,Short,4 or less,10. Mibe,40.0,62.0,2.0,4-2-3-1,65.0,13.0,NaN,NaN,NaN
21,ASU Sun Devils - TCU Frogs 1-2 (Team-based),22,Ball in play,114.021024,121.584812,Middle third,Left flank,Final third,Right flank,Short,4 or less,"2. S.Becerra, 23. Coppinger, 17. Patton",65.0,13.0,8.0,4-3-3,22.0,9.0,Medium,NaN,NaN
22,ASU Sun Devils - TCU Frogs 1-2 (Team-based),23,TCU Frogs - Possessions,114.021024,121.584812,Middle third,Left flank,Final third,Right flank,Short,4 or less,"2. S.Becerra, 23. Coppinger, 17. Patton",65.0,13.0,8.0,4-3-3,22.0,9.0,Medium,NaN,NaN
23,ASU Sun Devils - TCU Frogs 1-2 (Team-based),24,Ball in play,121.574812,125.684119,Own third,Left flank,Own third,Left flank,Short,4 or less,15. Nunley,22.0,9.0,4.0,4-2-3-1,84.0,58.0,Low,NaN,NaN
24,ASU Sun Devils - TCU Frogs 1-2 (Team-based),25,ASU Sun Devils - Possessions,121.574812,125.684119,Own third,Left flank,Own third,Left flank,Short,4 or less,15. Nunley,22.0,9.0,4.0,4-2-3-1,84.0,58.0,Low,NaN,NaN
25,ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
26,ASU Sun Devils - TCU Frogs 1-2 (Team-based),27,TCU Frogs - Possessions,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
27,ASU Sun Devils - TCU Frogs 1-2 (Team-based),28,TCU Frogs - Open play attacks,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
28,ASU Sun Devils - TCU Frogs 1-2 (Team-based),29,Ball in play,156.975876,161.550934,Middle third,Right flank,Final third,Center,Short,4 or less,"18. Monck, 11. Baltodano",41.0,59.0,4.0,4-2-3-1,33.0,33.0,Medium,NaN,NaN
29,ASU Sun Devils - TCU Frogs 1-2 (Team-based),30,ASU Sun Devils - Possessions,156.975876,161.550934,Middle third,Right flank,Final third,Center,Short,4 or less,"18. Monck, 11. Baltodano",41.0,59.0,4.0,4-2-3-1,33.0,33.0,Medium,NaN,NaN
30,ASU Sun Devils - TCU Frogs 1-2 (Team-based),31,Ball in play,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
31,ASU Sun Devils - TCU Frogs 1-2 (Team-based),32,TCU Frogs - Possessions,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
32,ASU Sun Devils - TCU Frogs 1-2 (Team-based),33,TCU Frogs - Highlights,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
33,ASU Sun Devils - TCU Frogs 1-2 (Team-based),34,TCU Frogs - Open play attacks,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
34,ASU Sun Devils - TCU Frogs 1-2 (Team-based),35,TCU Frogs - Shots,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
35,ASU Sun Devils - TCU Frogs 1-2 (Team-based),36,Ball in play,184.116732,200.634928,Own third,Center,Own third,Right flank,Medium,4 or less,"16. Nelles, 5. Fazackerley",2.0,33.0,16.0,4-2-3-1,80.0,19.0,Low,NaN,NaN
36,ASU Sun Devils - TCU Frogs 1-2 (Team-based),37,ASU Sun Devils - Possessions,184.116732,200.634928,Own third,Center,Own third,Right flank,Medium,4 or less,"16. Nelles, 5. Fazackerley",2.0,33.0,16.0,4-2-3-1,80.0,19.0,Low,NaN,NaN
37,ASU Sun Devils - TCU Frogs 1-2 (Team-based),38,ASU Sun Devils - Goalkeeper distributions,184.116732,200.634928,Own third,Center,Own third,Right flank,Medium,4 or less,"16. Nelles, 5. Fazackerley",2.0,33.0,16.0,4-2-3-1,80.0,19.0,Low,NaN,NaN
38,ASU Sun Devils - TCU Frogs 1-2 (Team-based),39,Ball in play,200.624928,218.532752,Final third,Left flank,Final third,Center,Medium,4 or less,"18. Yolinsky, 2. S.Becerra",80.0,19.0,13.0,4-3-3,3.0,35.0,High,Shot on goal,less than 0.1
39,ASU Sun Devils - TCU Frogs 1-2 (Team-based),40,TCU Frogs - Possessions,200.624928,218.532752,Final third,Left flank,Final third,Center,Medium,4 or less,"18. Yolinsky, 2. S.Becerra",80.0,19.0,13.0,4-3-3,3.0,35.0,High,Shot on goal,less than 0.1
40,ASU Sun Devils - TCU Frogs 1-2 (Team-based),41,TCU Frogs - Highlights,200.624928,218.532752,Final third,Left flank,Final third,Center,Medium,4 or less,"18. Yolinsky, 2. S.Becerra",80.0,19.0,13.0,4-3-3,3.0,35.0,High,Shot on goal,less than 0.1
41,ASU Sun Devils - TCU Frogs 1-2 (Team-based),42,TCU Frogs - Open play attacks,200.624928,218.532752,Final third,Left flank,Final third,Center,Medium,4 or less,"18. Yolinsky, 2. S.Becerra",80.0,19.0,13.0,4-3-3,3.0,35.0,High,Shot on goal,less than 0.1
42,ASU Sun Devils - TCU Frogs 1-2 (Team-based),43,TCU Frogs - Shots,200.624928,218.532752,Final third,Left flank,Final third,Center,Medium,4 or less,"18. Yolinsky, 2. S.Becerra",80.0,19.0,13.0,4-3-3,3.0,35.0,High,Shot on goal,less than 0.1
43,ASU Sun Devils - TCU Frogs 1-2 (Team-based),44,Ball in play,215.532752,234.126756,Own third,Center,Final third,Center,Medium,5-9,"16. Nelles, 5. Fazackerley, 7. Thomason",3.0,35.0,17.0,4-2-3-1,4.0,43.0,Low,NaN,NaN
44,ASU Sun Devils - TCU Frogs 1-2 (Team-based),45,ASU Sun Devils - Possessions,215.532752,234.126756,Own third,Center,Final third,Center,Medium,5-9,"16. Nelles, 5. Fazackerley, 7. Thomason",3.0,35.0,17.0,4-2-3-1,4.0,43.0,Low,NaN,NaN
45,ASU Sun Devils - TCU Frogs 1-2 (Team-based),46,ASU Sun Devils - Goalkeeper distributions,215.532752,234.126756,Own third,Center,Final third,Center,Medium,5-9,"16. Nelles, 5. Fazackerley, 7. Thomason",3.0,35.0,17.0,4-2-3-1,4.0,43.0,Low,NaN,NaN
46,ASU Sun Devils - TCU Frogs 1-2 (Team-based),47,Ball in play,234.116756,241.191438,Own third,Center,Own third,Left flank,Short,4 or less,17. Patton,4.0,43.0,4.0,4-3-3,21.0,0.0,NaN,NaN,NaN
47,ASU Sun Devils - TCU Frogs 1-2 (Team-based),48,TCU Frogs - Possessions,234.116756,241.191438,Own third,Center,Own third,Left flank,Short,4 or less,17. Patton,4.0,43.0,4.0,4-3-3,21.0,0.0,NaN,NaN,NaN
48,ASU Sun Devils - TCU Frogs 1-2 (Team-based),49,Ball in play,247.981215,257.130518,Final third,Right flank,Final third,Center,Short,4 or less,NaN,84.0,68.0,4.0,4-2-3-1,20.0,25.0,NaN,NaN,NaN
49,ASU Sun Devils - TCU Frogs 1-2 (Team-based),50,ASU Sun Devils - Possessions,247.981215,257.130518,Final third,Right flank,Final third,Center,Short,4 or less,NaN,84.0,68.0,4.0,4-2-3-1,20.0,25.0,NaN,NaN,NaN

In [64]:
# Rename columns
team_data = team_data.rename(columns={
    "start": "team_start",
    "end": "team_end"
})

# Keep only main possession rows
team_filtered = team_data[team_data["code"] == "Ball in play"]

# Cross join
merged = player_data.merge(team_filtered, how="cross")

# Time filter
merged = merged[
    (merged["Start Time"] >= merged["team_start"]) &
    (merged["Start Time"] <= merged["team_end"])
]

# Remove duplicates (FIXED)
merged = merged.sort_values(["Start Time", "team_start"]).drop_duplicates(
    subset=["ID_x", "Start Time", "Player Code", "Action Type"],
    keep="first"
).reset_index(drop=True)

In [66]:
merged.head(50)

,Source File,ID_x,Player Code,Start Time,End Time,Action Type,Additional Labels,match_name,ID_y,code,team_start,team_end,01 - Location third,02 - Location flank,03 - End location third,04 - End location flank,05 - Length,06 - Number of team events,10 - Players,11 - Start location X,12 - Start location Y,13 - Duration,14 - Formation,15 - End location X,16 - End location Y,08 - Transition,07 - Outcome,09 - xG
0,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,3,2. S.Becerra,42.139294,47.873396,Pass,"Back pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),3,Ball in play,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN
1,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,4,23. Coppinger,44.873396,49.873396,Pass,"Forward pass, Loss, Progressive pass, Short or...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),3,Ball in play,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN
2,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,5,11. Baltodano,46.655943,50.655943,Interception,Loss,ASU Sun Devils - TCU Frogs 1-2 (Team-based),3,Ball in play,42.008637,48.665943,Own third,Right flank,Own third,Right flank,Short,4 or less,"17. Patton, 2. S.Becerra, 23. Coppinger",16.0,68.0,5.0,4-3-3,97.0,8.0,NaN,NaN,NaN
3,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,7,19. Brown,57.874294,61.874294,Touch,Carry,ASU Sun Devils - TCU Frogs 1-2 (Team-based),9,Ball in play,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
4,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,8,19. Brown,59.973350,66.898939,Pass,"Lateral pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),9,Ball in play,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
5,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,9,23. Coppinger,63.898939,70.878258,Pass,"Lateral pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),9,Ball in play,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
6,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,10,19. Brown,67.878258,73.860254,Pass,"Lateral pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),9,Ball in play,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
7,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,11,23. Coppinger,70.860254,76.126548,Pass,"Lateral pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),9,Ball in play,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
8,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,14,11. Baltodano,72.075756,79.075756,Infraction,Foul,ASU Sun Devils - TCU Frogs 1-2 (Team-based),9,Ball in play,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
9,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,12,16. Sarinopoulos,74.126548,78.126548,Duel,"Foul suffered, Ground duel, Offensive duel",ASU Sun Devils - TCU Frogs 1-2 (Team-based),9,Ball in play,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
10,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,13,11. Baltodano,74.126548,78.126548,Duel,"Defensive duel, Ground duel",ASU Sun Devils - TCU Frogs 1-2 (Team-based),9,Ball in play,57.636425,77.085756,Own third,Center,Own third,Right flank,Medium,5-9,"1. Geller, 19. Brown, 23. Coppinger, 16. Sarin...",0.0,26.0,18.0,4-3-3,78.0,14.0,NaN,NaN,NaN
11,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,17,18. Yolinsky,95.650610,100.650610,Pass,"Forward pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),12,Ball in play,93.495669,103.516525,Own third,Center,Middle third,Left flank,Short,5-9,"23. Coppinger, 19. Brown, 18. Yolinsky, 9. Nor...",25.0,44.0,10.0,4-3-3,41.0,61.0,NaN,NaN,NaN
12,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,19,9. Norman,98.408438,103.408438,Pass,"Forward pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),12,Ball in play,93.495669,103.516525,Own third,Center,Middle third,Left flank,Short,5-9,"23. Coppinger, 19. Brown, 18. Yolinsky, 9. Nor...",25.0,44.0,10.0,4-3-3,41.0,61.0,NaN,NaN,NaN
13,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,18,9. Norman,98.439989,102.439989,Touch,Carry,ASU Sun Devils - TCU Frogs 1-2 (Team-based),12,Ball in play,93.495669,103.516525,Own third,Center,Middle third,Left flank,Short,5-9,"23. Coppinger, 19. Brown, 18. Yolinsky, 9. Nor...",25.0,44.0,10.0,4-3-3,41.0,61.0,NaN,NaN,NaN
14,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,20,10. Fuller,99.802489,104.802489,Pass,"Loss, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),12,Ball in play,93.495669,103.516525,Own third,Center,Middle third,Left flank,Short,5-9,"23. Coppinger, 19. Brown, 18. Yolinsky, 9. Nor...",25.0,44.0,10.0,4-3-3,41.0,61.0,NaN,NaN,NaN
15,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,21,20. Valladares,101.506525,105.506525,Interception,,ASU Sun Devils - TCU Frogs 1-2 (Team-based),12,Ball in play,93.495669,103.516525,Own third,Center,Middle third,Left flank,Short,5-9,"23. Coppinger, 19. Brown, 18. Yolinsky, 9. Nor...",25.0,44.0,10.0,4-3-3,41.0,61.0,NaN,NaN,NaN
16,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,23,10. Fuller,107.183646,112.183646,Pass,"Back pass, Loss, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),16,Ball in play,106.397360,110.846852,Middle third,Left flank,Middle third,Left flank,Short,4 or less,"9. Norman, 10. Fuller",64.0,0.0,3.0,4-3-3,40.0,62.0,NaN,NaN,NaN
17,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,24,10. Mibe,108.836852,112.836852,Interception,"Loss, Recovery, Counterpressing recovery",ASU Sun Devils - TCU Frogs 1-2 (Team-based),16,Ball in play,106.397360,110.846852,Middle third,Left flank,Middle third,Left flank,Short,4 or less,"9. Norman, 10. Fuller",64.0,0.0,3.0,4-3-3,40.0,62.0,NaN,NaN,NaN
18,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,25,2. S.Becerra,111.021024,117.059975,Pass,"Lateral pass, Recovery, Counterpressing recove...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),20,Ball in play,110.836852,114.031024,Middle third,Right flank,Middle third,Right flank,Short,4 or less,10. Mibe,40.0,62.0,2.0,4-2-3-1,65.0,13.0,NaN,NaN,NaN
19,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,26,23. Coppinger,114.059975,119.957367,Pass,"Lateral pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),22,Ball in play,114.021024,121.584812,Middle third,Left flank,Final third,Right flank,Short,4 or less,"2. S.Becerra, 23. Coppinger, 17. Patton",65.0,13.0,8.0,4-3-3,22.0,9.0,Medium,NaN,NaN
20,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,27,17. Patton,116.957367,121.957367,Pass,"Forward pass, Pass to final third, Progressive...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),22,Ball in play,114.021024,121.584812,Middle third,Left flank,Final third,Right flank,Short,4 or less,"2. S.Becerra, 23. Coppinger, 17. Patton",65.0,13.0,8.0,4-3-3,22.0,9.0,Medium,NaN,NaN
21,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,28,15. Nunley,119.574812,123.574812,Duel,"Defensive duel, Ground duel, Recovery",ASU Sun Devils - TCU Frogs 1-2 (Team-based),22,Ball in play,114.021024,121.584812,Middle third,Left flank,Final third,Right flank,Short,4 or less,"2. S.Becerra, 23. Coppinger, 17. Patton",65.0,13.0,8.0,4-3-3,22.0,9.0,Medium,NaN,NaN
22,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,29,15. Nunley,121.295870,125.295870,Touch,,ASU Sun Devils - TCU Frogs 1-2 (Team-based),22,Ball in play,114.021024,121.584812,Middle third,Left flank,Final third,Right flank,Short,4 or less,"2. S.Becerra, 23. Coppinger, 17. Patton",65.0,13.0,8.0,4-3-3,22.0,9.0,Medium,NaN,NaN
23,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,30,3. Hennessey,123.674119,127.674119,Duel,"Defensive duel, Ground duel, Recovery, Counter...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),24,Ball in play,121.574812,125.684119,Own third,Left flank,Own third,Left flank,Short,4 or less,15. Nunley,22.0,9.0,4.0,4-2-3-1,84.0,58.0,Low,NaN,NaN
24,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,31,15. Nunley,123.674119,127.674119,Duel,"Ground duel, Loss, Offensive duel",ASU Sun Devils - TCU Frogs 1-2 (Team-based),24,Ball in play,121.574812,125.684119,Own third,Left flank,Own third,Left flank,Short,4 or less,15. Nunley,22.0,9.0,4.0,4-2-3-1,84.0,58.0,Low,NaN,NaN
25,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,32,3. Hennessey,127.562850,133.865321,Pass,"Lateral pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
26,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,33,16. Sarinopoulos,130.865321,138.145922,Pass,"Back pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
27,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,34,19. Brown,135.145922,140.582951,Pass,"Lateral pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
28,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,35,23. Coppinger,137.582951,144.147343,Pass,"Forward pass, Pass to final third, Short or me...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
29,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,36,17. Patton,141.147343,146.685225,Pass,"Back pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
30,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,37,23. Coppinger,143.685225,152.480904,Pass,"Lateral pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
31,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,38,19. Brown,149.480904,155.753954,Pass,"Lateral pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
32,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,39,9. Norman,152.753954,157.753954,Pass,"Forward pass, Loss, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
33,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,40,18. Monck,153.975876,158.975876,Interception,"Forward pass, Pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
34,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,41,10. Fuller,155.589577,159.589577,Touch,,ASU Sun Devils - TCU Frogs 1-2 (Team-based),26,Ball in play,125.674119,156.985876,Final third,Right flank,Middle third,Left flank,Long,5-9,"3. Hennessey, 16. Sarinopoulos, 19. Brown, 23....",84.0,58.0,31.0,4-3-3,41.0,59.0,High,NaN,NaN
35,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,42,11. Baltodano,158.498263,162.498263,Interception,Loss,ASU Sun Devils - TCU Frogs 1-2 (Team-based),29,Ball in play,156.975876,161.550934,Middle third,Right flank,Final third,Center,Short,4 or less,"18. Monck, 11. Baltodano",41.0,59.0,4.0,4-2-3-1,33.0,33.0,Medium,NaN,NaN
36,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,43,16. Sarinopoulos,158.540934,164.498406,Pass,"Back pass, Recovery, Counterpressing recovery,...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),29,Ball in play,156.975876,161.550934,Middle third,Right flank,Final third,Center,Short,4 or less,"18. Monck, 11. Baltodano",41.0,59.0,4.0,4-2-3-1,33.0,33.0,Medium,NaN,NaN
37,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,44,1. Geller,161.498406,168.426428,Pass,"Forward pass, Goalkeeper action, Short or medi...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),29,Ball in play,156.975876,161.550934,Middle third,Right flank,Final third,Center,Short,4 or less,"18. Monck, 11. Baltodano",41.0,59.0,4.0,4-2-3-1,33.0,33.0,Medium,NaN,NaN
38,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,45,23. Coppinger,165.426428,174.745809,Pass,"Forward pass, Long pass, Pass to final third, ...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),31,Ball in play,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
39,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,46,7. Castain,171.745809,176.745809,Pass,"Back pass, Short or medium pass",ASU Sun Devils - TCU Frogs 1-2 (Team-based),31,Ball in play,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
40,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,47,3. Hennessey,173.299024,178.704493,Pass,Short or medium pass,ASU Sun Devils - TCU Frogs 1-2 (Team-based),31,Ball in play,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
41,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,51,10. Fuller,174.169173,188.169173,Shot,Opportunity,ASU Sun Devils - TCU Frogs 1-2 (Team-based),31,Ball in play,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
42,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,48,17. Patton,175.704493,181.042104,Pass,"Key pass, Lateral pass, Short or medium pass, ...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),31,Ball in play,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
43,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,49,6. Marcisz,178.791606,182.791606,Duel,"Defensive duel, Ground duel",ASU Sun Devils - TCU Frogs 1-2 (Team-based),31,Ball in play,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
44,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,50,10. Fuller,179.042104,183.042104,Duel,"Dribble, Ground duel, Offensive duel",ASU Sun Devils - TCU Frogs 1-2 (Team-based),31,Ball in play,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
45,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,52,16. Nelles,182.116732,186.116732,Shot against,"Goalkeeper action, Save",ASU Sun Devils - TCU Frogs 1-2 (Team-based),31,Ball in play,161.540934,187.116732,Own third,Center,Final third,Center,Long,5-9,"16. Sarinopoulos, 1. Geller, 23. Coppinger, 7....",33.0,33.0,22.0,4-3-3,2.0,33.0,Low,Shot on goal,less than 0.1
46,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,53,16. Nelles,192.461747,198.729780,Pass,"Goalkeeper action, Hand pass, Short or medium ...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),36,Ball in play,184.116732,200.634928,Own third,Center,Own third,Right flank,Medium,4 or less,"16. Nelles, 5. Fazackerley",2.0,33.0,16.0,4-2-3-1,80.0,19.0,Low,NaN,NaN
47,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,54,5. Fazackerley,195.729780,200.729780,Pass,"Lateral pass, Loss, Progressive pass, Short or...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),36,Ball in play,184.116732,200.634928,Own third,Center,Own third,Right flank,Medium,4 or less,"16. Nelles, 5. Fazackerley",2.0,33.0,16.0,4-2-3-1,80.0,19.0,Low,NaN,NaN
48,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,55,18. Yolinsky,198.624928,202.624928,Touch,Carry,ASU Sun Devils - TCU Frogs 1-2 (Team-based),36,Ball in play,184.116732,200.634928,Own third,Center,Own third,Right flank,Medium,4 or less,"16. Nelles, 5. Fazackerley",2.0,33.0,16.0,4-2-3-1,80.0,19.0,Low,NaN,NaN
49,ASU Sun Devils - TCU Frogs 1-2 (Player-based).xml,56,18. Yolinsky,203.879948,211.037246,Pass,"Lateral pass, Progressive pass, Short or mediu...",ASU Sun Devils - TCU Frogs 1-2 (Team-based),39,Ball in play,200.624928,218.532752,Final third,Left flank,Final third,Center,Medium,4 or less,"18. Yolinsky, 2. S.Becerra",80.0,19.0,13.0,4-3-3,3.0,35.0,High,Shot on goal,less than 0.1

In [67]:
merged.shape

(1365, 28)

# Analysis

In [19]:
print(player_data['Action Type'].unique())

<StringArray>
[           'Pass',            'Duel',           'Touch',        'Throw in',
    'Interception',          'Corner',            'Shot',    'Shot against',
       'Goal kick',         'Offside',       'Free kick',       'Clearance',
      'Infraction', 'Goalkeeper exit',    'Acceleration',               nan,
         'Penalty',        'Own goal']
Length: 18, dtype: str

In [28]:
unique_labels = sorted(
    set(
        label
        for sublist in player_data["Additional Labels"].dropna().str.split(", ")
        for label in sublist
    )
)

print(unique_labels)

['', 'Acceleration', 'Aerial duel', 'Assist', 'Back pass', 'Carry', 'Conceded goal', 'Counterpressing recovery', 'Cross', 'Cross blocked', 'Deep completed cross', 'Deep completion', 'Defensive duel', 'Dribble', 'Dribbled past attempt', 'Forward pass', 'Foul', 'Foul suffered', 'Free kick cross', 'Free kick shot', 'Goal', 'Goalkeeper action', 'Ground duel', 'Hand pass', 'Head pass', 'Head shot', 'Interception', 'Key pass', 'Lateral pass', 'Linkup play', 'Long pass', 'Loose ball duel', 'Loss', 'Offensive duel', 'Opportunity', 'Pass', 'Pass to final third', 'Pass to penalty area', 'Penalty conceded goal', 'Penalty foul', 'Penalty goal', 'Penalty save', 'Progressive pass', 'Progressive run', 'Recovery', 'Red card', 'Save', 'Save with reflex', 'Second assist', 'Short or medium pass', 'Shot', 'Shot after corner', 'Shot after free kick', 'Shot after throw in', 'Shot assist', 'Shot block', 'Sliding tackle', 'Smart pass', 'Third assist', 'Through pass', 'Touch in box', 'Under pressure', 'Yellow card']

In [25]:
player_data.iloc[50:100]

,Source File,ID,Player Code,Start Time,End Time,Action Type,Additional Labels
50,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,51,15. Hatteberg,112.027381,120.027381,Pass,"Cross, Deep completed cross, Lateral pass, Pas..."
51,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,52,10. Gaines,116.868753,120.868753,Duel,"Ground duel, Loss, Offensive duel"
52,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,53,15. Wilson,117.022061,122.022061,Pass,"Forward pass, Short or medium pass"
53,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,54,19. Arnst,119.194825,123.194825,Duel,Loose ball duel
54,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,55,40. Joseph,118.264297,124.058085,Pass,"Forward pass, Loss, Progressive pass, Short or..."
55,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,56,19. Arnst,121.058085,126.275690,Pass,"Lateral pass, Recovery, Short or medium pass"
56,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,57,5. Dorsey,123.275690,130.033335,Pass,"Lateral pass, Short or medium pass"
57,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,58,15. Hatteberg,127.033335,132.033335,Pass,"Forward pass, Progressive pass, Short or mediu..."
58,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,59,9. Boydstun,128.739713,135.013980,Pass,"Forward pass, Short or medium pass"
59,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,60,33. Calkins,132.013980,137.727669,Pass,"Back pass, Short or medium pass"
60,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,61,15. Hatteberg,135.727669,139.727669,Duel,"Dribble, Ground duel, Offensive duel, Carry"
61,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,62,5. Wright,137.008672,141.008672,Duel,"Defensive duel, Ground duel"
62,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,63,15. Hatteberg,135.278915,143.278915,Pass,"Cross, Lateral pass, Loss, Pass to penalty area"
63,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,64,25. Brown,140.468161,144.468161,Interception,Head pass
64,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,65,9. Boydstun,161.085444,176.085444,Corner,Shot assist
65,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,66,14. Baytosh,157.559686,171.559686,Shot,"Opportunity, Shot after corner, Touch in box"
66,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,67,0. Marks,164.728022,168.728022,Shot against,"Goalkeeper action, Save, Save with reflex"
67,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,68,17. Morris,188.589527,192.589527,Duel,"Ground duel, Offensive duel"
68,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,69,12. A.Hurge,188.921535,192.921535,Duel,"Defensive duel, Ground duel"
69,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,70,5. Dorsey,190.585237,194.585237,Duel,Loose ball duel
70,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,71,11. Wilson,190.623511,194.623511,Duel,Loose ball duel
71,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,72,14. Baytosh,190.673541,194.673541,Duel,"Loose ball duel, Sliding tackle"
72,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,73,5. Dorsey,191.006106,196.704945,Pass,"Recovery, Short or medium pass"
73,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,74,9. Boydstun,193.704945,198.704945,Pass,Short or medium pass
74,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,75,16. Brown,195.444050,246.051245,Pass,"Lateral pass, Progressive pass, Short or mediu..."
75,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,76,9. Boydstun,246.354604,251.354604,Pass,"Forward pass, Long pass, Pass to final third, ..."
76,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,77,18. Alvord,249.053430,253.053430,Duel,Loose ball duel
77,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,78,40. Joseph,250.675992,254.675992,Duel,"Defensive duel, Ground duel"
78,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,79,10. Gaines,251.502251,256.502251,Interception,"Pass, Short or medium pass"
79,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,80,11. Wilson,252.689496,256.689496,Duel,"Defensive duel, Ground duel, Recovery, Sliding..."
80,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,81,18. Alvord,254.371178,259.371178,Pass,Short or medium pass
81,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,82,5. Wright,255.757341,405.914134,Pass,"Forward pass, Pass to final third, Progressive..."
82,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,83,21. Thibeau,405.576077,418.554538,Pass,"Forward pass, Long pass, Loss, Pass to final t..."
83,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,84,31. Olivia,415.554538,421.761504,Interception,"Goalkeeper action, Hand pass, Lateral pass, Pa..."
84,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,85,12. A.Hurge,418.761504,423.773965,Pass,"Lateral pass, Short or medium pass"
85,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,86,16. Brown,421.773965,425.773965,Touch,Carry
86,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,87,16. Brown,423.202581,428.202581,Pass,Short or medium pass
87,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,88,9. Boydstun,424.266587,431.361664,Pass,Short or medium pass
88,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,89,16. Brown,428.361664,433.392085,Pass,"Forward pass, Long pass, Loss, Pass to final t..."
89,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,90,24. Geoffroy,430.392085,435.879233,Pass,"Head pass, Progressive pass, Short or medium pass"
90,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,91,33. Calkins,433.879233,437.879233,Duel,"Ground duel, Offensive duel"
91,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,92,21. Thibeau,434.135726,438.135726,Duel,"Defensive duel, Ground duel"
92,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,93,15. Hatteberg,446.428046,450.428046,Throw in,
93,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,94,2. Bedolla,447.932800,453.765778,Pass,"Back pass, Short or medium pass"
94,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,95,33. Calkins,450.765778,455.765778,Pass,"Back pass, Short or medium pass"
95,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,96,15. Hatteberg,452.737094,458.082308,Pass,"Pass to final third, Short or medium pass"
96,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,97,5. Dorsey,455.082308,462.024600,Pass,"Lateral pass, Short or medium pass"
97,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,98,12. A.Hurge,459.024600,464.024600,Pass,"Forward pass, Long pass, Loss, Pass to penalty..."
98,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,99,0. Marks,461.484847,465.484847,Interception,"Goalkeeper action, Recovery, Carry"
99,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,100,0. Marks,463.415010,471.561614,Pass,"Forward pass, Goalkeeper action, Long pass, Lo..."

In [23]:
player_data[player_data['Action Type']=='Shot']

,Source File,ID,Player Code,Start Time,End Time,Action Type,Additional Labels
65,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,66,14. Baytosh,157.559686,171.559686,Shot,"Opportunity, Shot after corner, Touch in box"
218,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,219,17. Morris,879.835251,893.835251,Shot,"Opportunity, Touch in box"
357,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,358,9. Boydstun,1439.488492,1453.488492,Shot,
362,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,363,9. Boydstun,1447.529968,1461.529968,Shot,
497,Arizona Wildcats - Oklahoma State Cowgirls 3-1...,498,2. Bedolla,2300.020895,2314.020895,Shot,"Shot after throw in, Touch in box"
...,...,...,...,...,...,...,...
52522,West Virginia Mountaineers - Kansas Jayhawks 0...,1344,23. Herrema,5372.962714,5386.962714,Shot,"Opportunity, Touch in box"
52560,West Virginia Mountaineers - Kansas Jayhawks 0...,1382,37. Hammontree,5575.054995,5595.054995,Shot,"Goal, Opportunity, Touch in box"
52568,West Virginia Mountaineers - Kansas Jayhawks 0...,1390,18. Watts,5656.577451,5676.577451,Shot,"Goal, Opportunity, Touch in box"
52612,West Virginia Mountaineers - Kansas Jayhawks 0...,1434,9. Olexa,5930.790209,5944.790209,Shot,"Head shot, Opportunity, Shot after free kick, ..."
52641,West Virginia Mountaineers - Kansas Jayhawks 0...,1463,5. White,6036.934197,6050.934197,Shot,Touch in box